language: php
php:
  - 7.1
  - 7.2
  - 7.3
env:
  - LARAVEL_VERSION=5.*
  - LARAVEL_VERSION=6.*

matrix:
  fast_finish: true
  exclude:
  - php: 7.1
    env: LARAVEL_VERSION=6.*
  - php: 7.3
    env: LARAVEL_VERSION=5.*

services:
  - mysql
  - mongodb
before_script:
  - pecl install mongodb
  - mysql -e 'CREATE DATABASE testing;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
    - composer update
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)