language: php
php:
  - 7.1
  - 7.3
services:
  - mysql
  - mongodb
before_script:
  - pecl install mongodb
  - mysql -e 'CREATE DATABASE testing;'
  - composer install --no-interaction
script:
  - vendor/bin/phpunit