version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  test:
    docker:
      - image: danielme/laravel-cli:latest
      - image: circleci/mongo:latest
      - image: circleci/mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''

    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Wait for Database Connection
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: mysql -h 127.0.0.1 -u root -e "create database testing"

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      
      - run: composer install --no-interaction
      - run: composer require jenssegers/mongodb --dev
      - run: composer require pcov/clobber --dev

      - save_cache:
              key: composer-v1-{{ checksum "composer.lock" }}
              paths:
                - vendor
                -
      - run: ./vendor/bin/pcov clobber

      - run:
          name: Run phpunit
          command: XDEBUG_MODE=coverage -dpcov.enabled=1 -dpcov.directory="./app" -dpcov.suffix=".php" vendor/bin/phpunit --coverage-clover=coverage.xml

      - codecov/upload:
          file: coverage.xml
workflows:
  test:
    jobs:
      - test